### ISSUE TITLE
Documentation > FR > Typo fix on intro.md

### ISSUE THREAD

**Issue by ghost** [vuejs-fr/vuex#20]
Bonjour,

   Tout d'abord, je tenais à vous féliciter pour l'excellente traduction FR que vous avez su apporter autour de vuex.

   Une petite correction sur le fichier intro.md a été apportée chez moi en local.

   Lorsque je fais un push (du fichier modifié contenu dans ma branche locale), j'obtiens un code erreur 403.
   
   ```
   git push --set-upstream origin doc_fr_intro  
   remote: Permission to vuejs-fr/vuex.git denied to ...
   fatal: unable to access 'https://github.com/vuejs-fr/vuex.git/': The requested URL returned error: 403
   ```

   Que dois-je faire de plus pour vous soumettre cette modification ?

Merci d'avance de votre retour.
:o )

**Comment by MachinisteWeb** [comment]
Bonjour @flyusfly. 

Merci pour ta participation !

Tu ne peux pas directement soumettre dans ce dossier. Tu n'as pas les droits. Tu dois faire un fork, faire une branche, puis faire une PR da ta branche vers `working`.

Cela t'aide ?

**Comment by ghost** [comment]
Bonjour @Haeresis,

Merci de ton retour : Cela m'a en effet aidé.

En conséquence, mini PR #21 soumise.

Bonne journée.
:o )
