### ISSUE TITLE
Traduction déjà existante

### ISSUE THREAD

**Issue by MachinisteWeb** [vuejs-fr/vuex#3]
Bonjour à tous !

tl;dr : pour aider à la traduction de la doc de Vuex passez ici : https://gitter.im/vuejs-fr/vue

J'ai Vue en dupliquant le dépôt de Vuex que l'utilisateur @darenju avait en grosse parti traduit la documentation et que les membres de Vuejs-FR suivant : @ALPIXELMaiki, @gbezyuk et @mdartic ont participés à la traduction de la documentation de Vuex ! (les PR sont listés sur cette page https://github.com/vuejs-fr/vuex/issues/1 en tant que crédit).

J'aimerai en savoir plus sur vos stratégies de traduction et de suivi de mise à jour de traduction. Si ce n'est que des pull requests ponctuelles des uns et des autres j'aimerai vous en dire un peu plus sur le fonctionnement de ce fork.

**Cas standard**

Nous travaillons directement pour les documentations annexes à la documentation principal de Vue dans le dossier `en` sous la branch `working`. Cela permet, quand un merge `upstream/dev` est fait sur `vuejs/vuex`, d'avoir des conflits sur les fichiers déjà traduit, et ainsi traqué les changement de la documentation `en`.

Quelqu'un s'occupe des traductions et soumet une PR sur `vuejs-fr/vuex:working`. On travail ensemble à la relecture et à la discussion du choix des termes à traduire ou non, etc. puis nous validons la PR.

Le fichier est ensuite reversé sur `vuejs-fr/vuex:dev` cette fois ci dans le dossier `fr`. Il ne reste plus qu'à faire une PR vers `vuejs/vuex:dev` pour mettre à jour la documentation.

**Cas de Vuex**

La traduction a déjà été faites et le dossier `fr` est en place et traduit. Ce que je vous propose c'est de rapatrier les fichiers du dossier `fr` de `vuejs/vuex:dev` vers le dossier `en` de `vuejs-fr/vuex:working` et de soumettre cela à PR.

Dans la PR nous pourrons relire ligne par ligne la traduction et vérifier que le nombre de ligne concorde et que tout est à jour. Ensuite le fichier suit le workflow habituel.

Au mieux il n'y aura pas de changement mais les changement de la traduction `en` seront traqués

**Traduction du site principal de Vue**

La traduction de https://fr.vuejs.org/ se fait un peu différemment aussi je vous invite à rejoindre le dépôt : https://github.com/vuejs-fr/vuejs.org si vous souhaitez participé. N'hésitez pas à venir sur le Chat français de Vue pour en discuter plus en détail : https://gitter.im/vuejs-fr/vue

**Comment by MachinisteWeb** [comment]
Enfin, j'imagine que c'est surement @darenju qui pourra répondre à ça. Bienvenue !

**Comment by darenju** [comment]
Merci, @Haeresis.

Alors, pour ma part, je souhaitais contribuer à Vuex, et j'ai vu que les documentations n'étaient pas traduites en français, alors j'ai entrepris une traduction sur mon temps libre et par plaisir personnel.

Je n'ai établi absolument aucune stratégie de mise à jour des fichiers, il faut donc voir ma contribution comme une sorte de "base de travail".

**Comment by MachinisteWeb** [comment]
Ok @darenju, on va faire des relectures de ton travail en vérifiant la concordance avec l'état « courant » dans un premier temps et ensuite on pourra maintenir ça en temps réel alors.

Merci beaucoup pour ta traduction et l'avancement !

**Comment by mdartic** [comment]
Hello all,

Pour ma part, j'avais juste vu une ou deux fautes que j'avais corrigé. Rien de bien conséquent, et aucune stratégie non plus.

Voyant l'initiative par contre, et ayant lu qqs issues sur la façon de contribuer, j'ai commencé à traduire la partie SSR. Une PR devrait pas trop tarder avec 2 pages traduites.
